### ISSUE TITLE
Wont work on Linux

### ISSUE THREAD

**Issue by R0N1n-dev** [Kholid060/projectile#12]
**Wont work on linux**
Provides an error about path variables

**To Reproduce**
1. Click on a project
2. Click to update dependancy

**Expected behavior**
Expect terminal to pen and process to begin

**Screenshots**
![projectile](https://user-images.githubusercontent.com/83344872/210943847-09ba37a7-22bc-41b3-be4c-9f57a6e9fff7.png)

**Desktop (please complete the following information):**
 - OS: ZorinOS 16
 - Version 0.2.0

**Additional context**

**Comment by shreyasm-dev** [comment]
Can you try adding those paths (/bin and /usr/bin) to PATH?

**Comment by R0N1n-dev** [comment]
I did try that

**Comment by R0N1n-dev** [comment]
And it still not working

**Comment by R0N1n-dev** [comment]
Unless am doing it wrong but i tried several times.

**Comment by R0N1n-dev** [comment]
This thing does not work

**Comment by R0N1n-dev** [comment]
No word
