### ISSUE TITLE
[Feature Request] macOS version

### ISSUE THREAD

**Issue by juanlatorre** [Kholid060/projectile#5]
Any chance to release a macOS version?

**Comment by Kholid060** [comment]
I don't have any mac device for debugging the app, so I don't really know whether the app will work when I build the mac version of it

**Comment by juanlatorre** [comment]
> I don't have any mac device for debugging the app, so I don't really know whether the app will work when I build the mac version of it

Need any help ? I've been testing the app on mac and it works fine 

![image](https://user-images.githubusercontent.com/4494526/132959389-0a2a1e47-7d12-4fb1-a097-7437618d178d.png)

**Comment by Kholid060** [comment]
> > I don't have any mac device for debugging the app, so I don't really know whether the app will work when I build the mac version of it
> 
> Need any help ? I've been testing the app on mac and it works fine
> 
> ![image](https://user-images.githubusercontent.com/4494526/132959389-0a2a1e47-7d12-4fb1-a097-7437618d178d.png)

That's good news, I'll add a mac version on the next release.

**Comment by juanlatorre** [comment]
Btw, this script will obviously only work on Windows, running `npx electron-rebuild` it's a good solution

`"rebuild": "./node_modules/.bin/electron-rebuild.cmd"`

**Comment by Kholid060** [comment]
I'll fix it
