### ISSUE TITLE
Project build output query

### ISSUE THREAD

**Issue by agreeff** [Kholid060/projectile#7]
hey @Kholid060, really sweet project here! only messed around with it briefly now, but I've got a feeling this will be a great help going forward.. 🍻 

this is not a "bug report" or "feature request" specifically, at the moment I'm just curious about something here: I see your `0.1.0` release has distributable packages for Windows and Mac, but not for Linux, but I also don't see any Linux config in `electron-buider.config.js`.

I don't see any CI-based build scripts in the repo, so just to check, do you have a plan in place to cater for this? or are you open to contributions here?

---

pretty sure I'm missing something with *your* defined build process here, however I did manage to successfully build, install, and run the `deb` target output on Linux, by first adding the following to the config:

```js
linux: {
  target: 'deb',
  category: 'Development',
}
```

then running `electron-builder build --config electron-builder.config.js --linux`.

note: the `electron-builder` [CLI docs](https://www.electron.build/cli.html) describes the `--dir` option as "Build unpacked dir. Useful to test.", which I had to exclude from the command to get any sort of "distributible package" out of it.

my current suggestion is to tweak the Node `package.json` scripts with the following:

```js
"scripts": {
 "electron:build": "electron-builder build --config electron-builder.config.js",
 "compile": "yarn electron:build --dir",
 "compile:linux": "yarn electron:build --linux",
 "compile:win": "yarn electron:build --win",
 "compile:mac": "yarn electron:build --mac",
}
```

also, since the project is using Yarn (I see `yarn.lock`), in the interest of consistency I opted to use the `yarn` CLI command here in place of `npm run`.

**Comment by agreeff** [comment]
eh.. I just realised I created this issue under the wrong GitHub account. I've been meaning to remove this and do everything with my primary account.. so when I get time to do that, please don't be confused when I suddenly reply as @ZaLiTHkA instead. 👍🏼

**Comment by Kholid060** [comment]
> I see your 0.1.0 release has distributable packages for Windows and Mac, but not for Linux, but I also don't see any Linux config in electron-buider.config.js

At first, when I created this project only have planned to only support Windows because I don't have the resource to debugging in the three different platforms. But because there's a request to add the mac version of the app (#5), that's why when v0.1.0 was released I added mac version.

> I don't see any CI-based build scripts in the repo, so just to check, do you have a plan in place to cater for this? or are you open to contributions here?

I currently don't have a plan for that, but a contribution is welcome.

**Comment by ZaLiTHkA** [comment]
awesome, well (on the correct account now), I'll do a little cleanup on my end and send you a PR for that a little later..

> At first, when I created this project only have planned to only support Windows because I don't have the resource to debugging in the three different platforms.

..and if you like, the majority of my projects are Node-powered, with my prefered dev environment being Linux. I do also have access to Wndows (10 and 11), and sporadic access to a 2017 iMac (can't remember version, but I know it can't run 11...). I don't mind helping test things if you need.

**Comment by Kholid060** [comment]
> ..and if you like, the majority of my projects are Node-powered, with my prefered dev environment being Linux. I do also have access to Wndows (10 and 11), and sporadic access to a 2017 iMac (can't remember version, but I know it can't run 11...). I don't mind helping test things if you need.

Thanks, I appreciate that.
